-- USER SQL
CREATE USER "SHERADOM" IDENTIFIED BY "sheradom"  
DEFAULT TABLESPACE "USERS";

-- QUOTAS
ALTER USER "SHERADOM" QUOTA UNLIMITED ON "USERS";

-- ROLES
GRANT "CONNECT" TO "SHERADOM" ;

-- SYSTEM PRIVILEGES
GRANT DROP ANY TRIGGER TO "SHERADOM" ;
GRANT CREATE TRIGGER TO "SHERADOM" ;
GRANT CREATE ANY PROCEDURE TO "SHERADOM" ;
GRANT CREATE ANY INDEX TO "SHERADOM" ;
GRANT CREATE TABLE TO "SHERADOM" ;
GRANT DROP ANY TABLE TO "SHERADOM" ;
GRANT CREATE TYPE TO "SHERADOM" ;
GRANT DROP ANY TYPE TO "SHERADOM" ;
GRANT EXECUTE ANY PROCEDURE TO "SHERADOM" ;
GRANT DROP ANY INDEX TO "SHERADOM" ;
GRANT INSERT ANY TABLE TO "SHERADOM" ;
GRANT DROP ANY PROCEDURE TO "SHERADOM" ;
GRANT CREATE ANY TRIGGER TO "SHERADOM" ;
GRANT CREATE ANY TABLE TO "SHERADOM" ;
GRANT CREATE ANY TYPE TO "SHERADOM" ;
